export const teams = [

/* ================= ACC ================= */
{ id:'bc', name:"Boston College", conf:"ACC", color:"#98002E", rating:67 },
{ id:'cal', name:"California", conf:"ACC", color:"#003262", rating:82 },
{ id:'clem', name:"Clemson", conf:"ACC", color:"#F56600", rating:82 },
{ id:'duke', name:"Duke", conf:"ACC", color:"#003087", rating:86 },
{ id:'fsu', name:"Florida State", conf:"ACC", color:"#782F40", rating:77 },
{ id:'gt', name:"Georgia Tech", conf:"ACC", color:"#B3A369", rating:88 },
{ id:'lou', name:"Louisville", conf:"ACC", color:"#AD0000", rating:88 },
{ id:'mia', name:"Miami", conf:"ACC", color:"#F47321", rating:95 },
{ id:'ncst', name:"NC State", conf:"ACC", color:"#CC0000", rating:85 },
{ id:'unc', name:"North Carolina", conf:"ACC", color:"#7BAFD4", rating:73 },
{ id:'pitt', name:"Pittsburgh", conf:"ACC", color:"#003594", rating:85 },
{ id:'smu', name:"SMU", conf:"ACC", color:"#C8102E", rating:88 },
{ id:'stan', name:"Stanford", conf:"ACC", color:"#8C1515", rating:73 },
{ id:'syr', name:"Syracuse", conf:"ACC", color:"#F76900", rating:70 },
{ id:'uva', name:"Virginia", conf:"ACC", color:"#232D4B", rating:91 },
{ id:'vtech', name:"Virginia Tech", conf:"ACC", color:"#630031", rating:70 },
{ id:'wake', name:"Wake Forest", conf:"ACC", color:"#9E7E38", rating:88 },

/* ================= AMERICAN ================= */
{ id:'army', name:"Army", conf:"American", color:"#D4BF91", rating:82 },
{ id:'char', name:"Charlotte", conf:"American", color:"#046A38", rating:63 },
{ id:'ecu', name:"East Carolina", conf:"American", color:"#592A8A", rating:88 },
{ id:'fau', name:"Florida Atlantic", conf:"American", color:"#003366", rating:73 },
{ id:'mem', name:"Memphis", conf:"American", color:"#003087", rating:85 },
{ id:'navy', name:"Navy", conf:"American", color:"#00205B", rating:94 },
{ id:'unt', name:"North Texas", conf:"American", color:"#00853E", rating:94 },
{ id:'rice', name:"Rice", conf:"American", color:"#00205B", rating:75 },
{ id:'usf', name:"South Florida", conf:"American", color:"#006747", rating:88 },
{ id:'temp', name:"Temple", conf:"American", color:"#9D2235", rating:77 },
{ id:'tulan', name:"Tulane", conf:"American", color:"#006747", rating:91 },
{ id:'tulsa', name:"Tulsa", conf:"American", color:"#002D62", rating:73 },
{ id:'uab', name:"UAB", conf:"American", color:"#1E4D2B", rating:73 },
{ id:'utsa', name:"UTSA", conf:"American", color:"#0C2340", rating:82 },

/* ================= BIG 12 ================= */
{ id:'asu', name:"Arizona State", conf:"Big 12", color:"#8C1D40", rating:85 },
{ id:'ariz', name:"Arizona", conf:"Big 12", color:"#CC0033", rating:88 },
{ id:'byu', name:"BYU", conf:"Big 12", color:"#002E5D", rating:94 },
{ id:'bay', name:"Baylor", conf:"Big 12", color:"#154734", rating:77 },
{ id:'cin', name:"Cincinnati", conf:"Big 12", color:"#E00122", rating:82 },
{ id:'col', name:"Colorado", conf:"Big 12", color:"#CFB87C", rating:70 },
{ id:'hou', name:"Houston", conf:"Big 12", color:"#C8102E", rating:91 },
{ id:'isu', name:"Iowa State", conf:"Big 12", color:"#C8102E", rating:87 },
{ id:'ku', name:"Kansas", conf:"Big 12", color:"#0051BA", rating:77 },
{ id:'ksu', name:"Kansas State", conf:"Big 12", color:"#512888", rating:80 },
{ id:'okst', name:"Oklahoma State", conf:"Big 12", color:"#FF6500", rating:63 },
{ id:'tcu', name:"TCU", conf:"Big 12", color:"#4D1979", rating:88 },
{ id:'ttu', name:"Texas Tech", conf:"Big 12", color:"#CC0000", rating:94 },
{ id:'ucf', name:"UCF", conf:"Big 12", color:"#BA9B37", rating:77 },
{ id:'utah', name:"Utah", conf:"Big 12", color:"#CC0000", rating:94 },
{ id:'wvu', name:"West Virginia", conf:"Big 12", color:"#002855", rating:73 },

/* ================= BIG TEN ================= */
{ id:'ill', name:"Illinois", conf:"Big Ten", color:"#E84A27", rating:88 },
{ id:'ind', name:"Indiana", conf:"Big Ten", color:"#990000", rating:100 },
{ id:'iowa', name:"Iowa", conf:"Big Ten", color:"#FFCD00", rating:88 },
{ id:'umd', name:"Maryland", conf:"Big Ten", color:"#E03A3E", rating:73 },
{ id:'msu', name:"Michigan State", conf:"Big Ten", color:"#18453B", rating:73 },
{ id:'mich', name:"Michigan", conf:"Big Ten", color:"#00274C", rating:88 },
{ id:'minn', name:"Minnesota", conf:"Big Ten", color:"#7A0019", rating:85 },
{ id:'neb', name:"Nebraska", conf:"Big Ten", color:"#E41C38", rating:82 },
{ id:'nw', name:"Northwestern", conf:"Big Ten", color:"#4E2A84", rating:82 },
{ id:'osu', name:"Ohio State", conf:"Big Ten", color:"#BB0000", rating:94 },
{ id:'ore', name:"Oregon", conf:"Big Ten", color:"#154733", rating:95 },
{ id:'psu', name:"Penn State", conf:"Big Ten", color:"#041E42", rating:82 },
{ id:'pur', name:"Purdue", conf:"Big Ten", color:"#CEB888", rating:67 },
{ id:'rut', name:"Rutgers", conf:"Big Ten", color:"#CC0033", rating:77 },
{ id:'ucla', name:"UCLA", conf:"Big Ten", color:"#2D68C4", rating:70 },
{ id:'usc', name:"USC", conf:"Big Ten", color:"#990000", rating:88 },
{ id:'wash', name:"Washington", conf:"Big Ten", color:"#4B2E83", rating:88 },
{ id:'wis', name:"Wisconsin", conf:"Big Ten", color:"#C5050C", rating:73 },

/* ================= CONFERENCE USA ================= */
{ id:'del', name:"Delaware", conf:"CUSA", color:"#00539B", rating:72 },
{ id:'fiu', name:"FIU", conf:"CUSA", color:"#081E3F", rating:82 },
{ id:'jax', name:"Jacksonville State", conf:"CUSA", color:"#CC0000", rating:86 },
{ id:'ken', name:"Kennesaw State", conf:"CUSA", color:"#FFC629", rating:89 },
{ id:'lib', name:"Liberty", conf:"CUSA", color:"#A6192E", rating:73 },
{ id:'latech', name:"Louisiana Tech", conf:"CUSA", color:"#002F8B", rating:85 },
{ id:'mtsu', name:"Middle Tennessee", conf:"CUSA", color:"#0066CC", rating:70 },
{ id:'most', name:"Missouri State", conf:"CUSA", color:"#5E0009", rating:70 },
{ id:'nmsu', name:"New Mexico State", conf:"CUSA", color:"#891216", rating:73 },
{ id:'samh', name:"Sam Houston", conf:"CUSA", color:"#F05A28", rating:67 },
{ id:'wku', name:"Western Kentucky", conf:"CUSA", color:"#E31837", rating:88 },

/* ================= MAC ================= */
{ id:'akron', name:"Akron", conf:"MAC", color:"#00285E", rating:77 },
{ id:'ball', name:"Ball State", conf:"MAC", color:"#BA0C2F", rating:73 },
{ id:'bg', name:"Bowling Green", conf:"MAC", color:"#4F2C1D", rating:73 },
{ id:'buff', name:"Buffalo", conf:"MAC", color:"#005BBB", rating:77 },
{ id:'cmu', name:"Central Michigan", conf:"MAC", color:"#6A0032", rating:82 },
{ id:'emu', name:"Eastern Michigan", conf:"MAC", color:"#006633", rating:73 },
{ id:'kent', name:"Kent State", conf:"MAC", color:"#002664", rating:77 },
{ id:'umass', name:"Massachusetts", conf:"MAC", color:"#881C1C", rating:60 },
{ id:'miamiOH', name:"Miami (OH)", conf:"MAC", color:"#B61E2E", rating:80 },
{ id:'ohio', name:"Ohio", conf:"MAC", color:"#00694E", rating:88 },
{ id:'sacst', name:"Sacramento State", conf:"MAC", color:"#043927", rating:75 }, 
{ id:'toledo', name:"Toledo", conf:"MAC", color:"#15397F", rating:85 },
{ id:'wmu', name:"Western Michigan", conf:"MAC", color:"#6C4023", rating:89 },

/* ================= MOUNTAIN WEST ================= */
{ id:'af', name:"Air Force", conf:"Mountain West", color:"#00308F", rating:73 },
{ id:'haw', name:"Hawai'i", conf:"Mountain West", color:"#024731", rating:88 },
{ id:'nev', name:"Nevada", conf:"Mountain West", color:"#003366", rating:70 },
{ id:'unm', name:"New Mexico", conf:"Mountain West", color:"#BA0C2F", rating:88 },
{ id:'niu', name:"Northern Illinois", conf:"Mountain West", color:"#BA0C2F", rating:70 },
{ id:'sjsu', name:"San José State", conf:"Mountain West", color:"#0055A2", rating:70 },
{ id:'unlv', name:"UNLV", conf:"Mountain West", color:"#CF0A2C", rating:89 },
{ id:'utep', name:"UTEP", conf:"Mountain West", color:"#041E42", rating:67 },
{ id:'wyo', name:"Wyoming", conf:"Mountain West", color:"#492F24", rating:73 },

/* ================= PAC-12 ================= */
{ id:'bsu', name:"Boise State", conf:"Pac-12", color:"#0033A0", rating:86 },
{ id:'csu', name:"Colorado State", conf:"Pac-12", color:"#1E4D2B", rating:67 },
{ id:'fres', name:"Fresno State", conf:"Pac-12", color:"#C41230", rating:88 },
{ id:'oreSt', name:"Oregon State", conf:"Pac-12", color:"#D73F09", rating:67 },
{ id:'sdsu', name:"San Diego State", conf:"Pac-12", color:"#A6192E", rating:88 },
{ id:'txst', name:"Texas State", conf:"Pac-12", color:"#501214", rating:82 },
{ id:'utst', name:"Utah State", conf:"Pac-12", color:"#00263A", rating:78 },
{ id:'washst', name:"Washington State", conf:"Pac-12", color:"#981E32", rating:82 },

/* ================= SEC ================= */
{ id:'ala', name:"Alabama", conf:"SEC", color:"#9E1B32", rating:89 },
{ id:'ark', name:"Arkansas", conf:"SEC", color:"#9D2235", rating:67 },
{ id:'aub', name:"Auburn", conf:"SEC", color:"#0C2340", rating:77 },
{ id:'fla', name:"Florida", conf:"SEC", color:"#0021A5", rating:73 },
{ id:'uga', name:"Georgia", conf:"SEC", color:"#BA0C2F", rating:94 },
{ id:'uk', name:"Kentucky", conf:"SEC", color:"#0033A0", rating:77 },
{ id:'lsu', name:"LSU", conf:"SEC", color:"#461D7C", rating:82 },
{ id:'msst', name:"Mississippi State", conf:"SEC", color:"#660000", rating:75 },
{ id:'mizz', name:"Missouri", conf:"SEC", color:"#F1B82D", rating:85 },
{ id:'ou', name:"Oklahoma", conf:"SEC", color:"#841617", rating:91 },
{ id:'miss', name:"Ole Miss", conf:"SEC", color:"#182B49", rating:95 },
{ id:'scar', name:"South Carolina", conf:"SEC", color:"#73000A", rating:73 },
{ id:'tenn', name:"Tennessee", conf:"SEC", color:"#FF8200", rating:85 },
{ id:'tamu', name:"Texas A&M", conf:"SEC", color:"#500000", rating:94 },
{ id:'tex', name:"Texas", conf:"SEC", color:"#BF5700", rating:109 },
{ id:'vandy', name:"Vanderbilt", conf:"SEC", color:"#866D4B", rating:91 },

/* ================= SUN BELT ================= */
{ id:'app', name:"App State", conf:"Sun Belt", color:"#FFCC00", rating:75 },
{ id:'arkst', name:"Arkansas State", conf:"Sun Belt", color:"#CC092F", rating:82 },
{ id:'coast', name:"Coastal Carolina", conf:"Sun Belt", color:"#00AEEF", rating:78 },
{ id:'gaso', name:"Georgia Southern", conf:"Sun Belt", color:"#041E42", rating:82 },
{ id:'gast', name:"Georgia State", conf:"Sun Belt", color:"#0039A6", rating:63 },
{ id:'jmu', name:"James Madison", conf:"Sun Belt", color:"#450084", rating:94 },
{ id:'ul', name:"Louisiana", conf:"Sun Belt", color:"#CE181E", rating:78 },
{ id:'marsh', name:"Marshall", conf:"Sun Belt", color:"#00B140", rating:77 },
{ id:'odu', name:"Old Dominion", conf:"Sun Belt", color:"#003057", rating:91 },
{ id:'usa', name:"South Alabama", conf:"Sun Belt", color:"#C8102E", rating:73 },
{ id:'usm', name:"Southern Miss", conf:"Sun Belt", color:"#FFAB00", rating:82 },
{ id:'troy', name:"Troy", conf:"Sun Belt", color:"#8B0000", rating:83 },
{ id:'ulm', name:"UL Monroe", conf:"Sun Belt", color:"#860038", rating:70 },

/* ================= INDEPENDENT ================= */
{ id:'nd', name:"Notre Dame", conf:"Independent", color:"#0C2340", rating:93 },
{ id:'conn', name:"UConn", conf:"Independent", color:"#000E2F", rating:88 }

];

export const masterSchedule = [
  // --- WEEK 0 / EARLY WEEK 1 ---
  { id: 1, date: "Aug 29", away: "unc", home: "tcu", location: "Dublin, Ireland", time: "TBD" },
  { id: 2, date: "Aug 29", away: "haw", home: "stan", location: "Stanford, CA", time: "TBD" },
  { id: 3, date: "Aug 29", away: "ncst", home: "uva", location: "Rio De Janeiro, Brazil", time: "TBD" },
  { id: 4, date: "Aug 29", away: "nmsu", home: "fsu", location: "Tallahassee, FL", time: "TBD" },

  // --- WEEK 1 THURSDAY/FRIDAY ---
  { id: 5, date: "Sep 3", away: "beth", home: "ucf", location: "Orlando, FL", time: "TBD" },
  { id: 6, date: "Sep 3", away: "idaho", home: "utah", location: "Salt Lake City, UT", time: "TBD" },
  { id: 7, date: "Sep 3", away: "col", home: "gt", location: "Atlanta, GA", time: "TBD" },
  { id: 8, date: "Sep 3", away: "akr", home: "wake", location: "Winston-Salem, NC", time: "TBD" },
  { id: 9, date: "Sep 3", away: "eiu", home: "minn", location: "Minneapolis, MN", time: "TBD" },
  { id: 10, date: "Sep 3", away: "umass", home: "rut", location: "Piscataway, NJ", time: "TBD" },
  { id: 11, date: "Sep 4", away: "liu", home: "ku", location: "Lawrence, KS", time: "TBD" },
  { id: 12, date: "Sep 4", away: "mia", home: "stan", location: "Stanford, CA", time: "TBD" },

  // --- WEEK 1 SATURDAY SLATE ---
  { id: 13, date: "Sep 5", away: "ecu", home: "ala", location: "Tuscaloosa, AL", time: "TBD" },
  { id: 14, date: "Sep 5", away: "nala", home: "ark", location: "Fayetteville, AR", time: "TBD" },
  { id: 15, date: "Sep 5", away: "bay", home: "aub", location: "Atlanta, GA", time: "TBD" },
  { id: 16, date: "Sep 5", away: "fau", home: "fla", location: "Gainesville, FL", time: "TBD" },
  { id: 17, date: "Sep 5", away: "tnst", home: "uga", location: "Athens, GA", time: "TBD" },
  { id: 18, date: "Sep 5", away: "ysu", home: "uk", location: "Lexington, KY", time: "TBD" },
  { id: 19, date: "Sep 5", away: "clem", home: "lsu", location: "Baton Rouge, LA", time: "TBD" },
  { id: 20, date: "Sep 5", away: "lou", home: "miss", location: "Nashville, TN", time: "TBD" },
  { id: 21, date: "Sep 5", away: "ulm", home: "msst", location: "Starkville, MS", time: "TBD" },
  { id: 22, date: "Sep 5", away: "uapb", home: "mizz", location: "Columbia, MO", time: "TBD" },
  { id: 23, date: "Sep 5", away: "utep", home: "ou", location: "Norman, OK", time: "TBD" },
  { id: 24, date: "Sep 5", away: "kent", home: "scar", location: "Columbia, SC", time: "TBD" },
  { id: 25, date: "Sep 5", away: "fur", home: "tenn", location: "Knoxville, TN", time: "TBD" },
  { id: 26, date: "Sep 5", away: "txst", home: "tex", location: "Austin, TX", time: "TBD" },
  { id: 27, date: "Sep 5", away: "most", home: "tamu", location: "College Station, TX", time: "TBD" },
  { id: 28, date: "Sep 5", away: "apeay", home: "vandy", location: "Nashville, TN", time: "TBD" },
  { id: 29, date: "Sep 5", away: "acu", home: "ttu", location: "Lubbock, TX", time: "TBD" },
  { id: 30, date: "Sep 5", away: "nich", home: "ksu", location: "Manhattan, KS", time: "TBD" },
  { id: 31, date: "Sep 5", away: "okst", home: "tulsa", location: "Tulsa, OK", time: "TBD" },
  { id: 32, date: "Sep 5", away: "nau", home: "ariz", location: "Tucson, AZ", time: "TBD" },
  { id: 33, date: "Sep 5", away: "morg", home: "asu", location: "Tempe, AZ", time: "TBD" },
  { id: 34, date: "Sep 5", away: "utech", home: "byu", location: "Provo, UT", time: "TBD" },
  { id: 35, date: "Sep 5", away: "bc", home: "cin", location: "Cincinnati, OH", time: "TBD" },
  { id: 36, date: "Sep 5", away: "orst", home: "hou", location: "Houston, TX", time: "TBD" },
  { id: 37, date: "Sep 5", away: "semo", home: "isu", location: "Ames, IA", time: "TBD" },
  { id: 38, date: "Sep 5", away: "coast", home: "wvu", location: "Morgantown, WV", time: "TBD" },
  { id: 39, date: "Sep 5", away: "mioh", home: "pitt", location: "Pittsburgh, PA", time: "TBD" },
  { id: 40, date: "Sep 5", away: "unh", home: "syr", location: "Syracuse, NY", time: "TBD" },
  { id: 41, date: "Sep 5", away: "tulan", home: "duke", location: "Durham, NC", time: "TBD" },
  { id: 42, date: "Sep 5", away: "ucla", home: "cal", location: "Berkeley, CA", time: "TBD" },
  { id: 43, date: "Sep 5", away: "vmi", home: "vtech", location: "Blacksburg, VA", time: "TBD" },
  { id: 44, date: "Sep 5", away: "uab", home: "ill", location: "Champaign, IL", time: "TBD" },
  { id: 45, date: "Sep 5", away: "unt", home: "ind", location: "Bloomington, IN", time: "TBD" },
  { id: 46, date: "Sep 5", away: "niu", home: "iowa", location: "Iowa City, IA", time: "TBD" },
  { id: 47, date: "Sep 5", away: "how", home: "umd", location: "College Park, MD", time: "TBD" },
  { id: 48, date: "Sep 5", away: "wmu", home: "mich", location: "Ann Arbor, MI", time: "TBD" },
  { id: 49, date: "Sep 5", away: "tol", home: "msu", location: "East Lansing, MI", time: "TBD" },
  { id: 50, date: "Sep 5", away: "ohio", home: "neb", location: "Lincoln, NE", time: "TBD" },
  { id: 51, date: "Sep 5", away: "sdst", home: "nw", location: "Evanston, IL", time: "TBD" },
  { id: 52, date: "Sep 5", away: "ball", home: "osu", location: "Columbus, OH", time: "TBD" },
  { id: 53, date: "Sep 5", away: "bsu", home: "ore", location: "Eugene, OR", time: "TBD" },
  { id: 54, date: "Sep 5", away: "marsh", home: "psu", location: "University Park, PA", time: "TBD" },
  { id: 55, date: "Sep 5", away: "inst", home: "pur", location: "West Lafayette, IN", time: "TBD" },
  { id: 56, date: "Sep 5", away: "fres", home: "usc", location: "Los Angeles, CA", time: "TBD" },
  { id: 57, date: "Sep 5", away: "wsu", home: "wash", location: "Seattle, WA", time: "TBD" },
  { id: 58, date: "Sep 5", away: "wyo", home: "csu", location: "Fort Collins, CO", time: "TBD" },
  { id: 59, date: "Sep 5", away: "portst", home: "sdsu", location: "San Diego, CA", time: "TBD" },
  { id: 60, date: "Sep 5", away: "idst", home: "utst", location: "Logan, UT", time: "TBD" },
  { id: 61, date: "Sep 5", away: "laf", home: "conn", location: "East Hartford, CT", time: "TBD" },

  // --- WEEK 1 SUNDAY/MONDAY ---
  { id: 62, date: "Sep 6", away: "nd", home: "wis", location: "Green Bay, WI", time: "TBD" },
  { id: 63, date: "Sep 7", away: "smu", home: "fsu", location: "Tallahassee, FL", time: "TBD" },

  // --- WEEK 2 ---
  { id: 64, date: "Sep 10", away: "famu", home: "mia", location: "Miami Gardens, FL", time: "TBD" },
  { id: 65, date: "Sep 11", away: "rut", home: "bc", location: "Chestnut Hill, MA", time: "TBD" },
  { id: 66, date: "Sep 11", away: "nova", home: "lou", location: "Louisville, KY", time: "TBD" },
  { id: 67, date: "Sep 12", away: "ark", home: "utah", location: "Salt Lake City, UT", time: "TBD" },
  { id: 68, date: "Sep 12", away: "usm", home: "aub", location: "Auburn, AL", time: "TBD" },
  { id: 69, date: "Sep 12", away: "camp", home: "fla", location: "Gainesville, FL", time: "TBD" },
  { id: 70, date: "Sep 12", away: "wku", home: "uga", location: "Athens, GA", time: "TBD" },
  { id: 71, date: "Sep 12", away: "ala", home: "uk", location: "Lexington, KY", time: "TBD" },
  { id: 72, date: "Sep 12", away: "latech", home: "lsu", location: "Baton Rouge, LA", time: "TBD" },
  { id: 73, date: "Sep 12", away: "char", home: "miss", location: "Oxford, MS", time: "TBD" },
  { id: 74, date: "Sep 12", away: "msst", home: "minn", location: "Minneapolis, MN", time: "TBD" },
  { id: 75, date: "Sep 12", away: "mizz", home: "ku", location: "Lawrence, KS", time: "TBD" },
  { id: 76, date: "Sep 12", away: "ou", home: "mich", location: "Ann Arbor, MI", time: "TBD" },
  { id: 77, date: "Sep 12", away: "tow", home: "scar", location: "Columbia, SC", time: "TBD" },
  { id: 78, date: "Sep 12", away: "tenn", home: "gt", location: "Atlanta, GA", time: "TBD" },
  { id: 79, date: "Sep 12", away: "osu", home: "tex", location: "Austin, TX", time: "TBD" },
  { id: 80, date: "Sep 12", away: "asu", home: "tamu", location: "College Station, TX", time: "TBD" },
  { id: 81, date: "Sep 12", away: "del", home: "vandy", location: "Nashville, TN", time: "TBD" },
  { id: 82, date: "Sep 12", away: "wsu", home: "ksu", location: "Manhattan, KS", time: "TBD" },
  { id: 83, date: "Sep 12", away: "ore", home: "okst", location: "Stillwater, OK", time: "TBD" },
  { id: 84, date: "Sep 12", away: "ttu", home: "orst", location: "Corvallis, OR", time: "TBD" },
  { id: 85, date: "Sep 12", away: "pvam", home: "bay", location: "Waco, TX", time: "TBD" },
  { id: 86, date: "Sep 12", away: "web", home: "col", location: "Boulder, CO", time: "TBD" },
  { id: 87, date: "Sep 12", away: "wcu", home: "cin", location: "Cincinnati, OH", time: "TBD" },
  { id: 88, date: "Sep 12", away: "south", home: "hou", location: "Houston, TX", time: "TBD" },
  { id: 89, date: "Sep 12", away: "isu", home: "iowa", location: "Iowa City, IA", time: "TBD" },
  { id: 90, date: "Sep 12", away: "gram", home: "tcu", location: "Fort Worth, TX", time: "TBD" },
  { id: 91, date: "Sep 12", away: "ucf", home: "pitt", location: "Pittsburgh, PA", time: "TBD" },
  { id: 92, date: "Sep 12", away: "utm", home: "wvu", location: "Morgantown, WV", time: "TBD" },
  { id: 93, date: "Sep 12", away: "ariz", home: "byu", location: "Provo, UT", time: "TBD" },
  { id: 94, date: "Sep 12", away: "cal", home: "syr", location: "Syracuse, NY", time: "TBD" },
  { id: 95, date: "Sep 12", away: "duke", home: "ill", location: "Champaign, IL", time: "TBD" },
  { id: 96, date: "Sep 12", away: "etsu", home: "unc", location: "Chapel Hill, NC", time: "TBD" },
  { id: 97, date: "Sep 12", away: "gaso", home: "clem", location: "Clemson, SC", time: "TBD" },
  { id: 98, date: "Sep 12", away: "nors", home: "uva", location: "Charlottesville, VA", time: "TBD" },
  { id: 99, date: "Sep 12", away: "odu", home: "vtech", location: "Blacksburg, VA", time: "TBD" },
  { id: 100, date: "Sep 12", away: "rich", home: "ncst", location: "Raleigh, NC", time: "TBD" },
  { id: 101, date: "Sep 12", away: "ucd", home: "smu", location: "Dallas, TX", time: "TBD" },
  { id: 102, date: "Sep 12", away: "wake", home: "pur", location: "West Lafayette, IN", time: "TBD" },
  { id: 103, date: "Sep 12", away: "how", home: "ind", location: "Bloomington, IN", time: "TBD" },
  { id: 104, date: "Sep 12", away: "emu", home: "msu", location: "East Lansing, MI", time: "TBD" },
  { id: 105, date: "Sep 12", away: "bgsu", home: "neb", location: "Lincoln, NE", time: "TBD" },
  { id: 106, date: "Sep 12", away: "psu", home: "temp", location: "Philadelphia, PA", time: "TBD" },
  { id: 107, date: "Sep 12", away: "sdsu", home: "ucla", location: "Pasadena, CA", time: "TBD" },
  { id: 108, date: "Sep 12", away: "umd", home: "conn", location: "East Hartford, CT", time: "TBD" },
  { id: 109, date: "Sep 12", away: "ul", home: "usc", location: "Los Angeles, CA", time: "TBD" },
  { id: 110, date: "Sep 12", away: "utst", home: "wash", location: "Seattle, WA", time: "TBD" },
  { id: 111, date: "Sep 12", away: "will", home: "wis", location: "Madison, WI", time: "TBD" },
  { id: 112, date: "Sep 12", away: "rice", home: "nd", location: "Notre Dame, IN", time: "TBD" },
  { id: 113, date: "Sep 12", away: "mem", home: "bsu", location: "Boise, ID", time: "TBD" },
  { id: 114, date: "Sep 12", away: "suu", home: "csu", location: "Fort Collins, CO", time: "TBD" },
  { id: 115, date: "Sep 12", away: "sac", home: "fres", location: "Fresno, CA", time: "TBD" },
  { id: 116, date: "Sep 12", away: "utsa", home: "txst", location: "San Marcos, TX", time: "TBD" },
  // --- WEEK 3 ---
  { id: 117, date: "Sep 17", away: "syr", home: "pitt", location: "Pittsburgh, PA", time: "TBD" },
  { id: 118, date: "Sep 18", away: "mia", home: "wake", location: "Winston-Salem, NC", time: "TBD" },
  
  // --- WEEK 3 SATURDAY SLATE ---
  { id: 119, date: "Sep 19", away: "fsu", home: "ala", location: "Tuscaloosa, AL", time: "TBD" },
  { id: 120, date: "Sep 19", away: "uga", home: "ark", location: "Fayetteville, AR", time: "TBD" },
  { id: 121, date: "Sep 19", away: "fla", home: "aub", location: "Auburn, AL", time: "TBD" },
  { id: 122, date: "Sep 19", away: "lsu", home: "miss", location: "Oxford, MS", time: "TBD" },
  { id: 123, date: "Sep 19", away: "troy", home: "mizz", location: "Columbia, MO", time: "TBD" },
  { id: 124, date: "Sep 19", away: "unm", home: "ou", location: "Norman, OK", time: "TBD" },
  { id: 125, date: "Sep 19", away: "msst", home: "scar", location: "Columbia, SC", time: "TBD" },
  { id: 126, date: "Sep 19", away: "kenn", home: "tenn", location: "Knoxville, TN", time: "TBD" },
  { id: 127, date: "Sep 19", away: "utsa", home: "tex", location: "Austin, TX", time: "TBD" },
  { id: 128, date: "Sep 19", away: "uk", home: "tamu", location: "College Station, TX", time: "TBD" },
  { id: 129, date: "Sep 19", away: "ncst", home: "vandy", location: "Nashville, TN", time: "TBD" },
  { id: 130, date: "Sep 19", away: "tulan", home: "ksu", location: "Manhattan, KS", time: "TBD" },
  { id: 131, date: "Sep 19", away: "niu", home: "ariz", location: "Tucson, AZ", time: "TBD" },
  { id: 132, date: "Sep 19", away: "latech", home: "bay", location: "Waco, TX", time: "TBD" },
  { id: 133, date: "Sep 19", away: "byu", home: "csu", location: "Fort Collins, CO", time: "TBD" },
  { id: 134, date: "Sep 19", away: "col", home: "nw", location: "Evanston, IL", time: "TBD" },
  { id: 135, date: "Sep 19", away: "mioh", home: "cin", location: "Cincinnati, OH", time: "TBD" },
  { id: 136, date: "Sep 19", away: "bgsu", home: "isu", location: "Ames, IA", time: "TBD" },
  { id: 137, date: "Sep 19", away: "arkst", home: "tcu", location: "Fort Worth, TX", time: "TBD" },
  { id: 138, date: "Sep 19", away: "gast", home: "ucf", location: "Orlando, FL", time: "TBD" },
  { id: 139, date: "Sep 19", away: "utst", home: "utah", location: "Salt Lake City, UT", time: "TBD" },
  { id: 140, date: "Sep 19", away: "uva", home: "wvu", location: "Charlotte, NC", time: "TBD" },
  { id: 141, date: "Sep 19", away: "murr", home: "okst", location: "Stillwater, OK", time: "TBD" },
  { id: 142, date: "Sep 19", away: "hou", home: "ttu", location: "Lubbock, TX", time: "TBD" },
  { id: 143, date: "Sep 19", away: "ku", home: "asu", location: "London, England", time: "TBD" },
  { id: 144, date: "Sep 19", away: "maine", home: "bc", location: "Chestnut Hill, MA", time: "TBD" },
  { id: 145, date: "Sep 19", away: "merc", home: "gt", location: "Atlanta, GA", time: "TBD" },
  { id: 146, date: "Sep 19", away: "unc", home: "clem", location: "Clemson, SC", time: "TBD" },
  { id: 147, date: "Sep 19", away: "smu", home: "lou", location: "Louisville, KY", time: "TBD" },
  { id: 148, date: "Sep 19", away: "stan", home: "duke", location: "Durham, NC", time: "TBD" },
  { id: 149, date: "Sep 19", away: "vtech", home: "umd", location: "College Park, MD", time: "TBD" },
  { id: 150, date: "Sep 19", away: "wagn", home: "cal", location: "Berkeley, CA", time: "TBD" },
  { id: 151, date: "Sep 19", away: "siu", home: "ill", location: "Champaign, IL", time: "TBD" },
  { id: 152, date: "Sep 19", away: "wku", home: "ind", location: "Bloomington, IN", time: "TBD" },
  { id: 153, date: "Sep 19", away: "utep", home: "mich", location: "Ann Arbor, MI", time: "TBD" },
  { id: 154, date: "Sep 19", away: "akr", home: "minn", location: "Minneapolis, MN", time: "TBD" },
  { id: 155, date: "Sep 19", away: "ndak", home: "neb", location: "Lincoln, NE", time: "TBD" },
  { id: 156, date: "Sep 19", away: "msu", home: "nd", location: "Notre Dame, IN", time: "TBD" },
  { id: 157, date: "Sep 19", away: "kent", home: "osu", location: "Columbus, OH", time: "TBD" },
  { id: 158, date: "Sep 19", away: "portst", home: "ore", location: "Eugene, OR", time: "TBD" },
  { id: 159, date: "Sep 19", away: "buff", home: "psu", location: "University Park, PA", time: "TBD" },
  { id: 160, date: "Sep 19", away: "usc", home: "rut", location: "Piscataway, NJ", time: "TBD" },
  { id: 161, date: "Sep 19", away: "pur", home: "ucla", location: "Pasadena, CA", time: "TBD" },
  { id: 162, date: "Sep 19", away: "ewu", home: "wash", location: "Seattle, WA", time: "TBD" },
  { id: 163, date: "Sep 19", away: "emu", home: "wis", location: "Madison, WI", time: "TBD" },
  { id: 164, date: "Sep 19", away: "uni", home: "iowa", location: "Iowa City, IA", time: "TBD" },
  { id: 165, date: "Sep 19", away: "sdak", home: "bsu", location: "Boise, ID", time: "TBD" },
  { id: 166, date: "Sep 19", away: "mont", home: "orst", location: "Corvallis, OR", time: "TBD" },
  { id: 167, date: "Sep 19", away: "jmu", home: "sdsu", location: "San Diego, CA", time: "TBD" },
  { id: 168, date: "Sep 19", away: "fres", home: "sjsu", location: "San Jose, CA", time: "TBD" },
  { id: 169, date: "Sep 19", away: "unt", home: "txst", location: "San Marcos, TX", time: "TBD" },
  { id: 170, date: "Sep 19", away: "duq", home: "wsu", location: "Pullman, WA", time: "TBD" },
  { id: 171, date: "Sep 19", away: "conn", home: "usm", location: "Hattiesburg, MS", time: "TBD" },
  // --- WEEK 4 FRIDAY ---
  { id: 172, date: "Sep 25", away: "clem", home: "cal", location: "Berkeley, CA", time: "TBD" },

  // --- WEEK 4 SATURDAY ---
  { id: 173, date: "Sep 26", away: "scar", home: "ala", location: "Tuscaloosa, AL", time: "TBD" },
  { id: 174, date: "Sep 26", away: "tulsa", home: "ark", location: "Fayetteville, AR", time: "TBD" },
  { id: 175, date: "Sep 26", away: "vandy", home: "aub", location: "Auburn, AL", time: "TBD" },
  { id: 176, date: "Sep 26", away: "miss", home: "fla", location: "Gainesville, FL", time: "TBD" },
  { id: 177, date: "Sep 26", away: "ou", home: "uga", location: "Athens, GA", time: "TBD" },
  { id: 178, date: "Sep 26", away: "usa", home: "uk", location: "Lexington, KY", time: "TBD" },
  { id: 179, date: "Sep 26", away: "tamu", home: "lsu", location: "Baton Rouge, LA", time: "TBD" },
  { id: 180, date: "Sep 26", away: "mizz", home: "msst", location: "Starkville, MS", time: "TBD" },
  { id: 181, date: "Sep 26", away: "tex", home: "tenn", location: "Knoxville, TN", time: "TBD" },
  { id: 182, date: "Sep 26", away: "ariz", home: "wsu", location: "Pullman, WA", time: "TBD" },
  { id: 183, date: "Sep 26", away: "samh", home: "ttu", location: "Lubbock, TX", time: "TBD" },
  { id: 184, date: "Sep 26", away: "hou", home: "gaso", location: "Statesboro, GA", time: "TBD" },
  { id: 185, date: "Sep 26", away: "col", home: "bay", location: "Waco, TX", time: "TBD" },
  { id: 186, date: "Sep 26", away: "ksu", home: "cin", location: "Cincinnati, OH", time: "TBD" },
  { id: 187, date: "Sep 26", away: "tcu", home: "ucf", location: "Orlando, FL", time: "TBD" },
  { id: 188, date: "Sep 26", away: "utah", home: "isu", location: "Ames, IA", time: "TBD" },
  { id: 189, date: "Sep 26", away: "okst", home: "wvu", location: "Morgantown, WV", time: "TBD" },
  { id: 190, date: "Sep 26", away: "app", home: "ncst", location: "Raleigh, NC", time: "TBD" },
  { id: 191, date: "Sep 26", away: "buck", home: "pitt", location: "Pittsburgh, PA", time: "TBD" },
  { id: 192, date: "Sep 26", away: "uark", home: "fsu", location: "Tallahassee, FL", time: "TBD" },
  { id: 193, date: "Sep 26", away: "cmu", home: "mia", location: "Miami Gardens, FL", time: "TBD" },
  { id: 194, date: "Sep 26", away: "del", home: "uva", location: "Charlottesville, VA", time: "TBD" },
  { id: 195, date: "Sep 26", away: "gt", home: "stan", location: "Stanford, CA", time: "TBD" },
  { id: 196, date: "Sep 26", away: "most", home: "smu", location: "Dallas, TX", time: "TBD" },
  { id: 197, date: "Sep 26", away: "vtech", home: "bc", location: "Chestnut Hill, MA", time: "TBD" },
  { id: 198, date: "Sep 26", away: "wake", home: "lou", location: "Louisville, KY", time: "TBD" },
  { id: 199, date: "Sep 26", away: "wm", home: "duke", location: "Durham, NC", time: "TBD" },
  { id: 200, date: "Sep 26", away: "nw", home: "ind", location: "Bloomington, IN", time: "TBD" },
  { id: 201, date: "Sep 26", away: "ucla", home: "umd", location: "College Park, MD", time: "TBD" },
  { id: 202, date: "Sep 26", away: "iowa", home: "mich", location: "Ann Arbor, MI", time: "TBD" },
  { id: 203, date: "Sep 26", away: "neb", home: "msu", location: "East Lansing, MI", time: "TBD" },
  { id: 204, date: "Sep 26", away: "ill", home: "osu", location: "Columbus, OH", time: "TBD" },
  { id: 205, date: "Sep 26", away: "wis", home: "psu", location: "University Park, PA", time: "TBD" },
  { id: 206, date: "Sep 26", away: "nd", home: "pur", location: "West Lafayette, IN", time: "TBD" },
  { id: 207, date: "Sep 26", away: "how", home: "rut", location: "Piscataway, NJ", time: "TBD" },
  { id: 208, date: "Sep 26", away: "ore", home: "usc", location: "Los Angeles, CA", time: "TBD" },
  { id: 209, date: "Sep 26", away: "minn", home: "wash", location: "Seattle, WA", time: "TBD" },
  { id: 210, date: "Sep 26", away: "rice", home: "fres", location: "Fresno, CA", time: "TBD" },
  { id: 211, date: "Sep 26", away: "uiw", home: "txst", location: "San Marcos, TX", time: "TBD" },
  { id: 212, date: "Sep 26", away: "sdsu", home: "tol", location: "Toledo, OH", time: "TBD" },
  { id: 213, date: "Sep 26", away: "troy", home: "utst", location: "Logan, UT", time: "TBD" },
  { id: 214, date: "Sep 26", away: "orst", home: "utep", location: "El Paso, TX", time: "TBD" },
  { id: 215, date: "Sep 26", away: "csu", home: "utsa", location: "San Antonio, TX", time: "TBD" },
  { id: 216, date: "Sep 26", away: "bsu", home: "wmu", location: "Kalamazoo, MI", time: "TBD" },
  { id: 217, date: "Sep 26", away: "conn", home: "mioh", location: "Oxford, OH", time: "TBD" },
  // --- WEEK 5 FRIDAY ---
  { id: 218, date: "Oct 2", away: "pitt", home: "vtech", location: "Blacksburg, VA", time: "TBD" },
  { id: 219, date: "Oct 2", away: "psu", home: "nw", location: "Evanston, IL", time: "TBD" },
  { id: 220, date: "Oct 2", away: "fres", home: "wsu", location: "Pullman, WA", time: "TBD" },

  // --- WEEK 5 SATURDAY ---
  { id: 221, date: "Oct 3", away: "vandy", home: "uga", location: "Athens, GA", time: "TBD" },
  { id: 222, date: "Oct 3", away: "mcne", home: "lsu", location: "Baton Rouge, LA", time: "TBD" },
  { id: 223, date: "Oct 3", away: "ala", home: "msst", location: "Starkville, MS", time: "TBD" },
  { id: 224, date: "Oct 3", away: "fla", home: "mizz", location: "Columbia, MO", time: "TBD" },
  { id: 225, date: "Oct 3", away: "uk", home: "scar", location: "Columbia, SC", time: "TBD" },
  { id: 226, date: "Oct 3", away: "aub", home: "tenn", location: "Knoxville, TN", time: "TBD" },
  { id: 227, date: "Oct 3", away: "ark", home: "tamu", location: "College Station, TX", time: "TBD" },
  { id: 228, date: "Oct 3", away: "mtsu", home: "ku", location: "Lawrence, KS", time: "TBD" },
  { id: 229, date: "Oct 3", away: "bay", home: "asu", location: "Tempe, AZ", time: "TBD" },
  { id: 230, date: "Oct 3", away: "byu", home: "tcu", location: "Fort Worth, TX", time: "TBD" },
  { id: 231, date: "Oct 3", away: "ucf", home: "hou", location: "Houston, TX", time: "TBD" },
  { id: 232, date: "Oct 3", away: "cin", home: "ariz", location: "Tucson, AZ", time: "TBD" },
  { id: 233, date: "Oct 3", away: "ttu", home: "col", location: "Boulder, CO", time: "TBD" },
  { id: 234, date: "Oct 3", away: "wvu", home: "isu", location: "Ames, IA", time: "TBD" },
  { id: 235, date: "Oct 3", away: "bc", home: "smu", location: "Dallas, TX", time: "TBD" },
  { id: 236, date: "Oct 3", away: "cal", home: "unlv", location: "Las Vegas, NV", time: "TBD" },
  { id: 237, date: "Oct 3", away: "lou", home: "ncst", location: "Raleigh, NC", time: "TBD" },
  { id: 238, date: "Oct 3", away: "mia", home: "clem", location: "Clemson, SC", time: "TBD" },
  { id: 239, date: "Oct 3", away: "nd", home: "unc", location: "Chapel Hill, NC", time: "TBD" },
  { id: 240, date: "Oct 3", away: "stan", home: "wake", location: "Winston-Salem, NC", time: "TBD" },
  { id: 241, date: "Oct 3", away: "syr", home: "conn", location: "East Hartford, CT", time: "TBD" },
  { id: 242, date: "Oct 3", away: "uva", home: "fsu", location: "Tallahassee, FL", time: "TBD" },
  { id: 243, date: "Oct 3", away: "pur", home: "ill", location: "Champaign, IL", time: "TBD" },
  { id: 244, date: "Oct 3", away: "osu", home: "iowa", location: "Iowa City, IA", time: "TBD" },
  { id: 245, date: "Oct 3", away: "mich", home: "minn", location: "Minneapolis, MN", time: "TBD" },
  { id: 246, date: "Oct 3", away: "umd", home: "neb", location: "Lincoln, NE", time: "TBD" },
  { id: 247, date: "Oct 3", away: "ind", home: "rut", location: "Piscataway, NJ", time: "TBD" },
  { id: 248, date: "Oct 3", away: "wash", home: "usc", location: "Los Angeles, CA", time: "TBD" },
  { id: 249, date: "Oct 3", away: "msu", home: "wis", location: "Madison, WI", time: "TBD" },
  { id: 250, date: "Oct 3", away: "utst", home: "bsu", location: "Boise, ID", time: "TBD" },
  { id: 251, date: "Oct 3", away: "orst", home: "csu", location: "Fort Collins, CO", time: "TBD" },
  { id: 252, date: "Oct 3", away: "txst", home: "sdsu", location: "San Diego, CA", time: "TBD" },
  // --- WEEK 6 FRIDAY ---
  { id: 253, date: "Oct 9", away: "fsu", home: "lou", location: "Louisville, KY", time: "TBD" },
  { id: 254, date: "Oct 9", away: "wsu", home: "utst", location: "Logan, UT", time: "TBD" },

  // --- WEEK 6 SATURDAY ---
  { id: 255, date: "Oct 10", away: "uga", home: "ala", location: "Tuscaloosa, AL", time: "TBD" },
  { id: 256, date: "Oct 10", away: "tenn", home: "ark", location: "Fayetteville, AR", time: "TBD" },
  { id: 257, date: "Oct 10", away: "scar", home: "fla", location: "Gainesville, FL", time: "TBD" },
  { id: 258, date: "Oct 10", away: "lsu", home: "uk", location: "Lexington, KY", time: "TBD" },
  { id: 259, date: "Oct 10", away: "tamu", home: "mizz", location: "Columbia, MO", time: "TBD" },
  { id: 260, date: "Oct 10", away: "tex", home: "ou", location: "Dallas, TX", time: "TBD" },
  { id: 261, date: "Oct 10", away: "miss", home: "vandy", location: "Nashville, TN", time: "TBD" },
  { id: 262, date: "Oct 10", away: "haw", home: "asu", location: "Tempe, AZ", time: "TBD" },
  { id: 263, date: "Oct 10", away: "ariz", home: "wvu", location: "Morgantown, WV", time: "TBD" },
  { id: 264, date: "Oct 10", away: "ucf", home: "okst", location: "Stillwater, OK", time: "TBD" },
  { id: 265, date: "Oct 10", away: "hou", home: "ksu", location: "Manhattan, KS", time: "TBD" },
  { id: 266, date: "Oct 10", away: "isu", home: "byu", location: "Provo, UT", time: "TBD" },
  { id: 267, date: "Oct 10", away: "ku", home: "utah", location: "Salt Lake City, UT", time: "TBD" },
  { id: 268, date: "Oct 10", away: "duke", home: "gt", location: "Atlanta, GA", time: "TBD" },
  { id: 269, date: "Oct 10", away: "unc", home: "pitt", location: "Pittsburgh, PA", time: "TBD" },
  { id: 270, date: "Oct 10", away: "stan", home: "nd", location: "Notre Dame, IN", time: "TBD" },
  { id: 271, date: "Oct 10", away: "syr", home: "uva", location: "Charlottesville, VA", time: "TBD" },
  { id: 272, date: "Oct 10", away: "vtech", home: "cal", location: "Berkeley, CA", time: "TBD" },
  { id: 273, date: "Oct 10", away: "wake", home: "ncst", location: "Raleigh, NC", time: "TBD" },
  { id: 274, date: "Oct 10", away: "ill", home: "msu", location: "East Lansing, MI", time: "TBD" },
  { id: 275, date: "Oct 10", away: "ind", home: "neb", location: "Lincoln, NE", time: "TBD" },
  { id: 276, date: "Oct 10", away: "ball", home: "nw", location: "Evanston, IL", time: "TBD" },
  { id: 277, date: "Oct 10", away: "umd", home: "osu", location: "Columbus, OH", time: "TBD" },
  { id: 278, date: "Oct 10", away: "ucla", home: "ore", location: "Eugene, OR", time: "TBD" },
  { id: 279, date: "Oct 10", away: "usc", home: "psu", location: "University Park, PA", time: "TBD" },
  { id: 280, date: "Oct 10", away: "minn", home: "pur", location: "West Lafayette, IN", time: "TBD" },
  { id: 281, date: "Oct 10", away: "iowa", home: "wash", location: "Seattle, WA", time: "TBD" },
  { id: 282, date: "Oct 10", away: "bsu", home: "fres", location: "Fresno, CA", time: "TBD" },
  { id: 283, date: "Oct 10", away: "sdsu", home: "orst", location: "Corvallis, OR", time: "TBD" },
  { id: 284, date: "Oct 10", away: "conn", home: "temp", location: "Philadelphia, PA", time: "TBD" },
  // --- WEEK 7 THURSDAY ---
  { id: 285, date: "Oct 15", away: "csu", home: "txst", location: "San Marcos, TX", time: "TBD" },

  // --- WEEK 7 SATURDAY ---
  { id: 286, date: "Oct 17", away: "aub", home: "uga", location: "Athens, GA", time: "TBD" },
  { id: 287, date: "Oct 17", away: "msst", home: "lsu", location: "Baton Rouge, LA", time: "TBD" },
  { id: 288, date: "Oct 17", away: "mizz", home: "miss", location: "Oxford, MS", time: "TBD" },
  { id: 289, date: "Oct 17", away: "uk", home: "ou", location: "Norman, OK", time: "TBD" },
  { id: 290, date: "Oct 17", away: "ala", home: "tenn", location: "Knoxville, TN", time: "TBD" },
  { id: 291, date: "Oct 17", away: "fla", home: "tex", location: "Austin, TX", time: "TBD" },
  { id: 292, date: "Oct 17", away: "cit", home: "tamu", location: "College Station, TX", time: "TBD" },
  { id: 293, date: "Oct 17", away: "ark", home: "vandy", location: "Nashville, TN", time: "TBD" },
  { id: 294, date: "Oct 17", away: "nd", home: "byu", location: "Provo, UT", time: "TBD" },
  { id: 295, date: "Oct 17", away: "asu", home: "ttu", location: "Lubbock, TX", time: "TBD" },
  { id: 296, date: "Oct 17", away: "cin", home: "wvu", location: "Morgantown, WV", time: "TBD" },
  { id: 297, date: "Oct 17", away: "ku", home: "ksu", location: "Manhattan, KS", time: "TBD" },
  { id: 298, date: "Oct 17", away: "okst", home: "hou", location: "Houston, TX", time: "TBD" },
  { id: 299, date: "Oct 17", away: "tcu", home: "bay", location: "Waco, TX", time: "TBD" },
  { id: 300, date: "Oct 17", away: "utah", home: "col", location: "Boulder, CO", time: "TBD" },
  { id: 301, date: "Oct 17", away: "chso", home: "clem", location: "Clemson, SC", time: "TBD" },
  { id: 302, date: "Oct 17", away: "elon", home: "stan", location: "Stanford, CA", time: "TBD" },
  { id: 303, date: "Oct 17", away: "fsu", home: "mia", location: "Miami Gardens, FL", time: "TBD" },
  { id: 304, date: "Oct 17", away: "gt", home: "vtech", location: "Blacksburg, VA", time: "TBD" },
  { id: 305, date: "Oct 17", away: "lou", home: "syr", location: "Syracuse, NY", time: "TBD" },
  { id: 306, date: "Oct 17", away: "unc", home: "duke", location: "Durham, NC", time: "TBD" },
  { id: 307, date: "Oct 17", away: "pitt", home: "bc", location: "Chestnut Hill, MA", time: "TBD" },
  { id: 308, date: "Oct 17", away: "uva", home: "smu", location: "Dallas, TX", time: "TBD" },
  { id: 309, date: "Oct 17", away: "wake", home: "cal", location: "Berkeley, CA", time: "TBD" },
  { id: 310, date: "Oct 17", away: "osu", home: "ind", location: "Bloomington, IN", time: "TBD" },
  { id: 311, date: "Oct 17", away: "rut", home: "umd", location: "College Park, MD", time: "TBD" },
  { id: 312, date: "Oct 17", away: "psu", home: "mich", location: "Ann Arbor, MI", time: "TBD" },
  { id: 313, date: "Oct 17", away: "nw", home: "msu", location: "East Lansing, MI", time: "TBD" },
  { id: 314, date: "Oct 17", away: "neb", home: "ore", location: "Eugene, OR", time: "TBD" },
  { id: 315, date: "Oct 17", away: "wash", home: "pur", location: "West Lafayette, IN", time: "TBD" },
  { id: 316, date: "Oct 17", away: "wis", home: "ucla", location: "Pasadena, CA", time: "TBD" },
  { id: 317, date: "Oct 17", away: "wsu", home: "orst", location: "Corvallis, OR", time: "TBD" },
  { id: 318, date: "Oct 17", away: "fres", home: "sdsu", location: "San Diego, CA", time: "TBD" },
  // --- WEEK 8 FRIDAY ---
  { id: 319, date: "Oct 23", away: "cal", home: "smu", location: "Dallas, TX", time: "TBD" },
  { id: 320, date: "Oct 23", away: "duke", home: "uva", location: "Charlottesville, VA", time: "TBD" },
  { id: 321, date: "Oct 23", away: "ncst", home: "stan", location: "Stanford, CA", time: "TBD" },

  // --- WEEK 8 SATURDAY ---
  { id: 322, date: "Oct 24", away: "tamu", home: "ala", location: "Tuscaloosa, AL", time: "TBD" },
  { id: 323, date: "Oct 24", away: "lsu", home: "aub", location: "Auburn, AL", time: "TBD" },
  { id: 324, date: "Oct 24", away: "vandy", home: "uk", location: "Lexington, KY", time: "TBD" },
  { id: 325, date: "Oct 24", away: "ou", home: "msst", location: "Starkville, MS", time: "TBD" },
  { id: 326, date: "Oct 24", away: "tenn", home: "scar", location: "Columbia, SC", time: "TBD" },
  { id: 327, date: "Oct 24", away: "miss", home: "tex", location: "Austin, TX", time: "TBD" },
  { id: 328, date: "Oct 24", away: "bay", home: "ku", location: "Lawrence, KS", time: "TBD" },
  { id: 329, date: "Oct 24", away: "byu", home: "ucf", location: "Orlando, FL", time: "TBD" },
  { id: 330, date: "Oct 24", away: "col", home: "okst", location: "Stillwater, OK", time: "TBD" },
  { id: 331, date: "Oct 24", away: "hou", home: "utah", location: "Salt Lake City, UT", time: "TBD" },
  { id: 332, date: "Oct 24", away: "isu", home: "ariz", location: "Tucson, AZ", time: "TBD" },
  { id: 333, date: "Oct 24", away: "ksu", home: "asu", location: "Tempe, AZ", time: "TBD" },
  { id: 334, date: "Oct 24", away: "ttu", home: "cin", location: "Cincinnati, OH", time: "TBD" },
  { id: 335, date: "Oct 24", away: "wvu", home: "tcu", location: "Fort Worth, TX", time: "TBD" },
  { id: 336, date: "Oct 24", away: "bc", home: "gt", location: "Atlanta, GA", time: "TBD" },
  { id: 337, date: "Oct 24", away: "pitt", home: "mia", location: "Miami Gardens, FL", time: "TBD" },
  { id: 338, date: "Oct 24", away: "syr", home: "unc", location: "Chapel Hill, NC", time: "TBD" },
  { id: 339, date: "Oct 24", away: "vtech", home: "clem", location: "Clemson, SC", time: "TBD" },
  { id: 340, date: "Oct 24", away: "ore", home: "ill", location: "Champaign, IL", time: "TBD" },
  { id: 341, date: "Oct 24", away: "ind", home: "mich", location: "Ann Arbor, MI", time: "TBD" },
  { id: 342, date: "Oct 24", away: "iowa", home: "minn", location: "Minneapolis, MN", time: "TBD" },
  { id: 343, date: "Oct 24", away: "rut", home: "nw", location: "Evanston, IL", time: "TBD" },
  { id: 344, date: "Oct 24", away: "msu", home: "ucla", location: "Pasadena, CA", time: "TBD" },
  { id: 345, date: "Oct 24", away: "usc", home: "wis", location: "Madison, WI", time: "TBD" },
  { id: 346, date: "Oct 24", away: "sdsu", home: "csu", location: "Fort Collins, CO", time: "TBD" },
  { id: 347, id: 347, date: "Oct 24", away: "utst", home: "txst", location: "San Marcos, TX", time: "TBD" },
  { id: 348, date: "Oct 24", away: "bsu", home: "wsu", location: "Pullman, WA", time: "TBD" },
  { id: 349, date: "Oct 24", away: "umass", home: "conn", location: "East Hartford, CT", time: "TBD" },
  // --- WEEK 9 FRIDAY ---
  { id: 350, date: "Oct 30", away: "cal", home: "ncst", location: "Raleigh, NC", time: "TBD" },
  { id: 351, date: "Oct 30", away: "smu", home: "syr", location: "Syracuse, NY", time: "TBD" },
  { id: 352, date: "Oct 30", away: "orst", home: "fres", location: "Fresno, CA", time: "TBD" },

  // --- WEEK 9 SATURDAY (HALLOWEEN) ---
  { id: 353, date: "Oct 31", away: "mizz", home: "ark", location: "Fayetteville, AR", time: "TBD" },
  { id: 354, date: "Oct 31", away: "fla", home: "uga", location: "Atlanta, GA", time: "TBD" },
  { id: 355, date: "Oct 31", away: "aub", home: "miss", location: "Oxford, MS", time: "TBD" },
  { id: 356, date: "Oct 31", away: "scar", home: "ou", location: "Norman, OK", time: "TBD" },
  { id: 357, date: "Oct 31", away: "msst", home: "tex", location: "Austin, TX", time: "TBD" },
  { id: 358, date: "Oct 31", away: "ariz", home: "ttu", location: "Lubbock, TX", time: "TBD" },
  { id: 359, date: "Oct 31", away: "asu", home: "byu", location: "Provo, UT", time: "TBD" },
  { id: 360, date: "Oct 31", away: "bay", home: "ucf", location: "Orlando, FL", time: "TBD" },
  { id: 361, date: "Oct 31", away: "ku", home: "tcu", location: "Fort Worth, TX", time: "TBD" },
  { id: 362, date: "Oct 31", away: "ksu", home: "col", location: "Boulder, CO", time: "TBD" },
  { id: 363, date: "Oct 31", away: "okst", home: "isu", location: "Ames, IA", time: "TBD" },
  { id: 364, date: "Oct 31", away: "utah", home: "cin", location: "Cincinnati, OH", time: "TBD" },
  { id: 365, date: "Oct 31", away: "bc", home: "duke", location: "Durham, NC", time: "TBD" },
  { id: 366, date: "Oct 31", away: "clem", home: "fsu", location: "Tallahassee, FL", time: "TBD" },
  { id: 367, date: "Oct 31", away: "gt", home: "pitt", location: "Pittsburgh, PA", time: "TBD" },
  { id: 368, date: "Oct 31", away: "mia", home: "unc", location: "Chapel Hill, NC", time: "TBD" },
  { id: 369, date: "Oct 31", away: "stan", home: "lou", location: "Louisville, KY", time: "TBD" },
  { id: 370, date: "Oct 31", away: "uva", home: "wake", location: "Winston-Salem, NC", time: "TBD" },
  { id: 371, date: "Oct 31", away: "minn", home: "ind", location: "Bloomington, IN", time: "TBD" },
  { id: 372, date: "Oct 31", away: "wis", home: "iowa", location: "Iowa City, IA", time: "TBD" },
  { id: 373, date: "Oct 31", away: "ill", home: "umd", location: "College Park, MD", time: "TBD" },
  { id: 374, date: "Oct 31", away: "wash", home: "neb", location: "Lincoln, NE", time: "TBD" },
  { id: 375, date: "Oct 31", away: "nw", home: "ore", location: "Eugene, OR", time: "TBD" },
  { id: 376, date: "Oct 31", away: "pur", home: "psu", location: "University Park, PA", time: "TBD" },
  { id: 377, date: "Oct 31", away: "mich", home: "rut", location: "Piscataway, NJ", time: "TBD" },
  { id: 378, date: "Oct 31", away: "nev", home: "ucla", location: "Pasadena, CA", time: "TBD" },
  { id: 379, date: "Oct 31", away: "osu", home: "usc", location: "Los Angeles, CA", time: "TBD" },
  { id: 380, date: "Oct 31", away: "navy", home: "nd", location: "Foxborough, MA", time: "TBD" },
  { id: 381, date: "Oct 31", away: "txst", home: "bsu", location: "Boise, ID", time: "TBD" },
  { id: 382, date: "Oct 31", away: "wsu", home: "sdsu", location: "San Diego, CA", time: "TBD" },
  { id: 383, date: "Oct 31", away: "csu", home: "utst", location: "Logan, UT", time: "TBD" },
  { id: 384, date: "Oct 31", away: "conn", home: "af", location: "USAF Academy, CO", time: "TBD" },
  // --- WEEK 10 FRIDAY ---
  { id: 385, date: "Nov 6", away: "clem", home: "syr", location: "Syracuse, NY", time: "TBD" },
  { id: 386, date: "Nov 6", away: "duke", home: "ncst", location: "Raleigh, NC", time: "TBD" },
  { id: 387, date: "Nov 6", away: "lou", home: "gt", location: "Atlanta, GA", time: "TBD" },
  { id: 388, date: "Nov 6", away: "vtech", home: "smu", location: "Dallas, TX", time: "TBD" },

  // --- WEEK 10 SATURDAY ---
  { id: 389, date: "Nov 7", away: "ark", home: "aub", location: "Auburn, AL", time: "TBD" },
  { id: 390, date: "Nov 7", away: "ou", home: "fla", location: "Gainesville, FL", time: "TBD" },
  { id: 391, date: "Nov 7", away: "ala", home: "lsu", location: "Baton Rouge, LA", time: "TBD" },
  { id: 392, date: "Nov 7", away: "uga", home: "miss", location: "Oxford, MS", time: "TBD" },
  { id: 393, date: "Nov 7", away: "vandy", home: "msst", location: "Starkville, MS", time: "TBD" },
  { id: 394, date: "Nov 7", away: "tex", home: "mizz", location: "Columbia, MO", time: "TBD" },
  { id: 395, date: "Nov 7", away: "tamu", home: "scar", location: "Columbia, SC", time: "TBD" },
  { id: 396, date: "Nov 7", away: "uk", home: "tenn", location: "Knoxville, TN", time: "TBD" },
  { id: 397, date: "Nov 7", away: "byu", home: "utah", location: "Salt Lake City, UT", time: "TBD" },
  { id: 398, date: "Nov 7", away: "ucf", home: "ku", location: "Lawrence, KS", time: "TBD" },
  { id: 399, date: "Nov 7", away: "cin", home: "hou", location: "Houston, TX", time: "TBD" },
  { id: 400, date: "Nov 7", away: "col", home: "asu", location: "Tempe, AZ", time: "TBD" },
  { id: 401, date: "Nov 7", away: "isu", home: "bay", location: "Waco, TX", time: "TBD" },
  { id: 402, date: "Nov 7", away: "okst", home: "ksu", location: "Manhattan, KS", time: "TBD" },
  { id: 403, date: "Nov 7", away: "tcu", home: "ariz", location: "Tucson, AZ", time: "TBD" },
  { id: 404, date: "Nov 7", away: "wvu", home: "ttu", location: "Lubbock, TX", time: "TBD" },
  { id: 405, date: "Nov 7", away: "fsu", home: "bc", location: "Chestnut Hill, MA", time: "TBD" },
  { id: 406, date: "Nov 7", away: "merri", home: "wake", location: "Winston-Salem, NC", time: "TBD" },
  { id: 407, date: "Nov 7", away: "mia", home: "nd", location: "Notre Dame, IN", time: "TBD" },
  { id: 408, date: "Nov 7", away: "unc", home: "conn", location: "East Hartford, CT", time: "TBD" },
  { id: 409, date: "Nov 7", away: "neb", home: "ill", location: "Champaign, IL", time: "TBD" },
  { id: 410, date: "Nov 7", away: "msu", home: "mich", location: "Ann Arbor, MI", time: "TBD" },
  { id: 411, date: "Nov 7", away: "ucla", home: "minn", location: "Minneapolis, MN", time: "TBD" },
  { id: 412, date: "Nov 7", away: "iowa", home: "nw", location: "Evanston, IL", time: "TBD" },
  { id: 413, date: "Nov 7", away: "ore", home: "osu", location: "Columbus, OH", time: "TBD" },
  { id: 414, date: "Nov 7", away: "umd", home: "pur", location: "West Lafayette, IN", time: "TBD" },
  { id: 415, date: "Nov 7", away: "psu", home: "wash", location: "Seattle, WA", time: "TBD" },
  { id: 416, date: "Nov 7", away: "rut", home: "wis", location: "Madison, WI", time: "TBD" },
  { id: 417, date: "Nov 7", away: "bsu", home: "csu", location: "Fort Collins, CO", time: "TBD" },
  { id: 418, date: "Nov 7", away: "txst", home: "orst", location: "Corvallis, OR", time: "TBD" },
  { id: 419, date: "Nov 7", away: "fres", home: "utst", location: "Logan, UT", time: "TBD" },
  // --- WEEK 11 FRIDAY ---
  { id: 420, date: "Nov 13", away: "fsu", home: "pitt", location: "Pittsburgh, PA", time: "TBD" },

  // --- WEEK 11 SATURDAY ---
  { id: 421, date: "Nov 14", away: "asu", home: "ucf", location: "Orlando, FL", time: "TBD" },
  { id: 422, date: "Nov 14", away: "bay", home: "byu", location: "Provo, UT", time: "TBD" },
  { id: 423, date: "Nov 14", away: "cin", home: "isu", location: "Ames, IA", time: "TBD" },
  { id: 424, date: "Nov 14", away: "hou", home: "col", location: "Boulder, CO", time: "TBD" },
  { id: 425, date: "Nov 14", away: "ku", home: "wvu", location: "Morgantown, WV", time: "TBD" },
  { id: 426, date: "Nov 14", away: "ksu", home: "tcu", location: "Fort Worth, TX", time: "TBD" },
  { id: 427, date: "Nov 14", away: "ttu", home: "okst", location: "Stillwater, OK", time: "TBD" },
  { id: 428, date: "Nov 14", away: "utah", home: "ariz", location: "Tucson, AZ", time: "TBD" },
  { id: 429, date: "Nov 14", away: "scar", home: "ark", location: "Fayetteville, AR", time: "TBD" },
  { id: 430, date: "Nov 14", away: "mizz", home: "uga", location: "Athens, GA", time: "TBD" },
  { id: 431, date: "Nov 14", away: "fla", home: "uk", location: "Lexington, KY", time: "TBD" },
  { id: 432, date: "Nov 14", away: "tex", home: "lsu", location: "Baton Rouge, LA", time: "TBD" },
  { id: 433, date: "Nov 14", away: "aub", home: "msst", location: "Starkville, MS", time: "TBD" },
  { id: 434, date: "Nov 14", away: "miss", home: "ou", location: "Norman, OK", time: "TBD" },
  { id: 435, date: "Nov 14", away: "tenn", home: "tamu", location: "College Station, TX", time: "TBD" },
  { id: 436, date: "Nov 14", away: "ala", home: "vandy", location: "Nashville, TN", time: "TBD" },
  { id: 437, date: "Nov 14", away: "bc", home: "nd", location: "Notre Dame, IN", time: "TBD" },
  { id: 438, date: "Nov 14", away: "cal", home: "uva", location: "Charlottesville, VA", time: "TBD" },
  { id: 439, date: "Nov 14", away: "duke", home: "mia", location: "Miami Gardens, FL", time: "TBD" },
  { id: 440, date: "Nov 14", away: "gt", home: "clem", location: "Clemson, SC", time: "TBD" },
  { id: 441, date: "Nov 14", away: "lou", home: "unc", location: "Chapel Hill, NC", time: "TBD" },
  { id: 442, date: "Nov 14", away: "stan", home: "vtech", location: "Blacksburg, VA", time: "TBD" },
  { id: 443, date: "Nov 14", away: "syr", home: "ncst", location: "Raleigh, NC", time: "TBD" },
  { id: 444, date: "Nov 14", away: "wake", home: "smu", location: "Dallas, TX", time: "TBD" },
  { id: 445, date: "Nov 14", away: "usc", home: "ind", location: "Bloomington, IN", time: "TBD" },
  { id: 446, date: "Nov 14", away: "pur", home: "iowa", location: "Iowa City, IA", time: "TBD" },
  { id: 447, date: "Nov 14", away: "wis", home: "umd", location: "College Park, MD", time: "TBD" },
  { id: 448, date: "Nov 14", away: "wash", home: "msu", location: "East Lansing, MI", time: "TBD" },
  { id: 449, date: "Nov 14", away: "nw", home: "osu", location: "Columbus, OH", time: "TBD" },
  { id: 450, date: "Nov 14", away: "mich", home: "ore", location: "Eugene, OR", time: "TBD" },
  { id: 451, date: "Nov 14", away: "minn", home: "psu", location: "University Park, PA", time: "TBD" },
  { id: 452, date: "Nov 14", away: "neb", home: "rut", location: "Piscataway, NJ", time: "TBD" },
  { id: 453, date: "Nov 14", away: "ill", home: "ucla", location: "Pasadena, CA", time: "TBD" },
  { id: 454, date: "Nov 14", away: "orst", home: "bsu", location: "Boise, ID", time: "TBD" },
  { id: 455, date: "Nov 14", away: "utst", home: "sdsu", location: "San Diego, CA", time: "TBD" },
  { id: 456, date: "Nov 14", away: "fres", home: "txst", location: "San Marcos, TX", time: "TBD" },
  { id: 457, date: "Nov 14", away: "csu", home: "wsu", location: "Pullman, WA", time: "TBD" },
  { id: 458, date: "Nov 14", away: "jmu", home: "conn", location: "East Hartford, CT", time: "TBD" },
  // --- WEEK 12 FRIDAY ---
  { id: 459, date: "Nov 20", away: "vtech", home: "mia", location: "Miami Gardens, FL", time: "TBD" },
  { id: 460, date: "Nov 20", away: "sdsu", home: "bsu", location: "Boise, ID", time: "TBD" },

  // --- WEEK 12 SATURDAY ---
  { id: 461, date: "Nov 21", away: "chatt", home: "ala", location: "Tuscaloosa, AL", time: "TBD" },
  { id: 462, date: "Nov 21", away: "samf", home: "aub", location: "Auburn, AL", time: "TBD" },
  { id: 463, date: "Nov 21", away: "vandy", home: "fla", location: "Gainesville, FL", time: "TBD" },
  { id: 464, date: "Nov 21", away: "woff", home: "miss", location: "Oxford, MS", time: "TBD" },
  { id: 465, date: "Nov 21", away: "tntech", home: "msst", location: "Starkville, MS", time: "TBD" },
  { id: 466, date: "Nov 21", away: "uk", home: "mizz", location: "Columbia, MO", time: "TBD" },
  { id: 467, date: "Nov 21", away: "tamu", home: "ou", location: "Norman, OK", time: "TBD" },
  { id: 468, date: "Nov 21", away: "uga", home: "scar", location: "Columbia, SC", time: "TBD" },
  { id: 469, date: "Nov 21", away: "lsu", home: "tenn", location: "Knoxville, TN", time: "TBD" },
  { id: 470, date: "Nov 21", away: "ark", home: "tex", location: "Austin, TX", time: "TBD" },
  { id: 471, date: "Nov 21", away: "ariz", home: "ksu", location: "Manhattan, KS", time: "TBD" },
  { id: 472, date: "Nov 21", away: "byu", home: "ku", location: "Lawrence, KS", time: "TBD" },
  { id: 473, date: "Nov 21", away: "col", home: "cin", location: "Cincinnati, OH", time: "TBD" },
  { id: 474, date: "Nov 21", away: "hou", home: "wvu", location: "Morgantown, WV", time: "TBD" },
  { id: 475, date: "Nov 21", away: "isu", home: "ucf", location: "Orlando, FL", time: "TBD" },
  { id: 476, date: "Nov 21", away: "okst", home: "asu", location: "Tempe, AZ", time: "TBD" },
  { id: 477, date: "Nov 21", away: "ttu", home: "bay", location: "Waco, TX", time: "TBD" },
  { id: 478, date: "Nov 21", away: "utah", home: "tcu", location: "Fort Worth, TX", time: "TBD" },
  { id: 479, date: "Nov 21", away: "clem", home: "duke", location: "Durham, NC", time: "TBD" },
  { id: 480, date: "Nov 21", away: "ncst", home: "fsu", location: "Tallahassee, FL", time: "TBD" },
  { id: 481, date: "Nov 21", away: "unc", home: "uva", location: "Charlottesville, VA", time: "TBD" },
  { id: 482, date: "Nov 21", away: "pitt", home: "lou", location: "Louisville, KY", time: "TBD" },
  { id: 483, date: "Nov 21", away: "smu", home: "nd", location: "Notre Dame, IN", time: "TBD" },
  { id: 484, date: "Nov 21", away: "stan", home: "cal", location: "Berkeley, CA", time: "TBD" },
  { id: 485, date: "Nov 21", away: "syr", home: "bc", location: "Chestnut Hill, MA", time: "TBD" },
  { id: 486, date: "Nov 21", away: "wake", home: "gt", location: "Atlanta, GA", time: "TBD" },
  { id: 487, date: "Nov 21", away: "iowa", home: "ill", location: "Champaign, IL", time: "TBD" },
  { id: 488, date: "Nov 21", away: "ucla", home: "mich", location: "Ann Arbor, MI", time: "TBD" },
  { id: 489, date: "Nov 21", away: "ore", home: "msu", location: "East Lansing, MI", time: "TBD" },
  { id: 490, date: "Nov 21", away: "nw", home: "minn", location: "Minneapolis, MN", time: "TBD" },
  { id: 491, date: "Nov 21", away: "osu", home: "neb", location: "Lincoln, NE", time: "TBD" },
  { id: 492, date: "Nov 21", away: "rut", home: "psu", location: "University Park, PA", time: "TBD" },
  { id: 493, date: "Nov 21", away: "wis", home: "pur", location: "West Lafayette, IN", time: "TBD" },
  { id: 494, date: "Nov 21", away: "umd", home: "usc", location: "Los Angeles, CA", time: "TBD" },
  { id: 495, date: "Nov 21", away: "ind", home: "wash", location: "Seattle, WA", time: "TBD" },
  { id: 496, date: "Nov 21", away: "csu", home: "fres", location: "Fresno, CA", time: "TBD" },
  { id: 497, date: "Nov 21", away: "utst", home: "orst", location: "Corvallis, OR", time: "TBD" },
  { id: 498, date: "Nov 21", away: "wsu", home: "txst", location: "San Marcos, TX", time: "TBD" },
  { id: 499, date: "Nov 21", away: "odu", home: "conn", location: "East Hartford, CT", time: "TBD" },
  // --- WEEK 13 FRIDAY (THANKSGIVING WEEKEND) ---
  { id: 500, date: "Nov 27", away: "tex", home: "tamu", location: "College Station, TX", time: "TBD" },
  { id: 501, date: "Nov 27", away: "fla", home: "fsu", location: "Tallahassee, FL", time: "TBD" },
  { id: 502, date: "Nov 27", away: "msst", home: "miss", location: "Oxford, MS", time: "TBD" },
  { id: 503, date: "Nov 27", away: "neb", home: "iowa", location: "Iowa City, IA", time: "TBD" },

  // --- WEEK 13 SATURDAY (RIVALRY SATURDAY) ---
  { id: 504, date: "Nov 28", away: "aub", home: "ala", location: "Tuscaloosa, AL", time: "TBD" },
  { id: 505, date: "Nov 28", away: "lsu", home: "ark", location: "Fayetteville, AR", time: "TBD" },
  { id: 506, date: "Nov 28", away: "gt", home: "uga", location: "Athens, GA", time: "TBD" },
  { id: 507, date: "Nov 28", away: "lou", home: "uk", location: "Lexington, KY", time: "TBD" },
  { id: 508, date: "Nov 28", away: "ou", home: "mizz", location: "Columbia, MO", time: "TBD" },
  { id: 509, date: "Nov 28", away: "scar", home: "clem", location: "Clemson, SC", time: "TBD" },
  { id: 510, date: "Nov 28", away: "tenn", home: "vandy", location: "Nashville, TN", time: "TBD" },
  { id: 511, date: "Nov 28", away: "asu", home: "ariz", location: "Tucson, AZ", time: "TBD" },
  { id: 512, date: "Nov 28", away: "bay", home: "hou", location: "Houston, TX", time: "TBD" },
  { id: 513, date: "Nov 28", away: "ucf", home: "col", location: "Boulder, CO", time: "TBD" },
  { id: 514, date: "Nov 28", away: "cin", home: "byu", location: "Provo, UT", time: "TBD" },
  { id: 515, date: "Nov 28", away: "ku", home: "okst", location: "Stillwater, OK", time: "TBD" },
  { id: 516, date: "Nov 28", away: "ksu", home: "isu", location: "Ames, IA", time: "TBD" },
  { id: 517, date: "Nov 28", away: "tcu", home: "ttu", location: "Lubbock, TX", time: "TBD" },
  { id: 518, date: "Nov 28", away: "wvu", home: "utah", location: "Salt Lake City, UT", time: "TBD" },
  { id: 519, date: "Nov 28", away: "bc", home: "mia", location: "Miami Gardens, FL", time: "TBD" },
  { id: 520, date: "Nov 28", away: "duke", home: "wake", location: "Winston-Salem, NC", time: "TBD" },
  { id: 521, date: "Nov 28", away: "ncst", home: "unc", location: "Chapel Hill, NC", time: "TBD" },
  { id: 522, date: "Nov 28", away: "nd", home: "syr", location: "Syracuse, NY", time: "TBD" },
  { id: 523, date: "Nov 28", away: "pitt", home: "cal", location: "Berkeley, CA", time: "TBD" },
  { id: 524, date: "Nov 28", away: "smu", home: "stan", location: "Stanford, CA", time: "TBD" },
  { id: 525, date: "Nov 28", away: "uva", home: "vtech", location: "Blacksburg, VA", time: "TBD" },
  { id: 526, date: "Nov 28", away: "nw", home: "ill", location: "Champaign, IL", time: "TBD" },
  { id: 527, date: "Nov 28", away: "pur", home: "ind", location: "Bloomington, IN", time: "TBD" },
  { id: 528, date: "Nov 28", away: "psu", home: "umd", location: "College Park, MD", time: "TBD" },
  { id: 529, date: "Nov 28", away: "mich", home: "osu", location: "Columbus, OH", time: "TBD" },
  { id: 530, date: "Nov 28", away: "wash", home: "ore", location: "Eugene, OR", time: "TBD" },
  { id: 531, date: "Nov 28", away: "msu", home: "rut", location: "Piscataway, NJ", time: "TBD" },
  { id: 532, date: "Nov 28", away: "usc", home: "ucla", location: "Pasadena, CA", time: "TBD" },
  { id: 533, date: "Nov 28", away: "minn", home: "wis", location: "Madison, WI", time: "TBD" },
  { id: 534, date: "Nov 28", away: "tbd", home: "csu", location: "Fort Collins, CO", time: "TBD" },
  { id: 535, date: "Nov 28", away: "tbd", home: "fres", location: "Fresno, CA", time: "TBD" },
  { id: 536, date: "Nov 28", away: "tbd", home: "utst", location: "Logan, UT", time: "TBD" },
  { id: 537, date: "Nov 28", away: "tbd", home: "wsu", location: "Pullman, WA", time: "TBD" },
  { id: 538, date: "Nov 28", away: "conn", home: "wyo", location: "Laramie, WY", time: "TBD" }
];